# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='questiontop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ask_students.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_images'),
        ),
    ]
