# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ask_students', '0002_auto_20190228_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='Student', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='edited',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='answered',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ask_students.Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='edited',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
